<?php
class	XunfangModel extends Model{
			protected $_validate = array(
			//array('num','require','工位必须填写！'),
			//array('num','number','必须是数字格式！'),
			//array('username','','员工编号已经存在！',0,'unique',1),			
			//array('yourname','','员工姓名有重名！',0,'unique',1),
			//array('password','require','密码不能为空！'),
			//array('password','passwords','密码不一致',0,'confirm'), // 验证确认密码是否和密码一致
			//array('uid',array(1,2,3),'值的范围不正确！',2,'in'),
			array('gongsiname','require','公司名称必须填写哦~'),
			array('gongsihangye','require','公司所属行业必须填写哦~'),
			array('gongsizhineng','require','所属职能线必须填写哦~'),
			array('gongsijob','require','客户职位必须填写哦~'),
			array('gongsineed','require','需要人数必须填写哦~'),
			array('jobxingzhi','require','职位性质必须选择哦~'),
			array('bumen','require','所在部门必须填写哦~'),
			array('jobnum','require','招聘人数必须填写哦~'),
			array('xueli','require','学历要求必须选择哦~'),
			array('zhuanye','require','专业要求必须填写哦~'),
			array('age_a','require','年龄范围必须填写哦~'),
			array('age_b','require','年龄范围必须填写哦~'),
			array('zhengshuneed','require','证书要求必须填写哦~'),
			array('jobage','require','工作岗位或年限必须填写哦~'),
			array('guanji','require','候选人贯籍必须填写哦~'),
			array('mubiaogongsi','require','候选人目标企业名称必须填写哦~'),
			array('mubiaojiagou','require','是否提供候选人目标企业架构必须选择哦~'),
			array('mubiaobumen','require','是否提供候选人对标部门名称必须选择哦~'),
			array('bushurenshu','require','部属人数必须填写哦~'),
			array('opendate','require','职位开放日期必须填写哦~'),
			array('jinji','require','职位紧急程度必须选择哦~'),
			array('offdate','require','职位关闭日期必须填写哦~'),
			array('liucheng','require','流程中候选人情况必须填写哦~'),
			array('offer','require','是否有过offer必须选择哦~'),
			array('moeny_a','require','年薪范围必须填写哦~'),
			array('moeny_b','require','年薪范围必须填写哦~'),
			array('liucheng','require','流程中候选人情况必须填写哦~'),
			array('gongsineed','number','需要人数必须是数字格式！'),
			array('age_a','number','年龄范围必须是数字格式！'),
			array('age_b','number','年龄范围必须是数字格式！'),
			array('jobnum','number','招聘人数必须是数字格式！'),
			array('jobage','number','工作岗位或年限必须是数字格式！'),
			array('bushurenshu','number','部属人数必须是数字格式!'),
			array('moeny_a','number','年薪范围必须是数字格式!'),
			array('moeny_b','number','年薪范围必须是数字格式!'),

	);
}
